### ISSUE TITLE
[Error] php8: not found

### ISSUE THREAD

**Issue by aldinokemal** [erseco/alpine-moodle#16]
moodle_1   | Generating config.php file...
moodle_1   | /docker-entrypoint-init.d/02-configure-moodle.sh: line 23: php8: not found

<img width="647" alt="image" src="https://user-images.githubusercontent.com/14232125/172030858-4a30025f-8603-4aaa-b785-df9910bf7c2b.png">

**Comment by aldinokemal** [comment]
I think you need to change php8 become php81

**Comment by erseco** [comment]
The **php81** version is in beta, because moodle is not fully supporting it, so I fixed the [erseco/alpine-php-webserver](https://github.com/erseco/alpine-php-webserver) base image to the **1.13.0** version, you should now be able to build it. 

If you want to test the **php81** you can check the [php81](https://github.com/erseco/alpine-moodle/tree/php81) branch. 

Best regards.
